version: '3.8'
services:
  nginx:
    container_name: webserver
    build:
      context: ./frontend/Year3_dev_Frontend/main/react-admin/nginx
    ports:
      - 3000:80
    depends_on:
      - backend
    volumes:
      - ./frontend/Year3_dev_Frontend/main/react-admin/build:/usr/share/nginx/html
      - ./frontend/Year3_dev_Frontend/main/react-admin/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
  backend:
    container_name: smartfarm
    build:
      context: ./Backend
    volumes:
      - ./Backend:/usr/src/app/
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - mosquitto
      - my-postgres
    env_file:
      - ./Backend/.env
    networks:
      - mynetwork

  my-postgres:
    image: postgres
    container_name: database
    volumes:
      - psql-db:/var/lib/postgresql
    env_file:
      - ./Backend/.env
    networks:
      - mynetwork

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  psql-db:
